name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install libmosquitto-dev

      - name: Configure
        run: |
          cmake -B build

      - name: Build
        run: |
          cmake --build build
